alpakatest_EXTERNAL_DEPENDS := TBB ALPAKA BOOST BACKTRACE
ifdef CUDA_BASE
alpakatest_EXTERNAL_DEPENDS += CUDA
endif
ifdef ROCM_BASE
alpakatest_EXTERNAL_DEPENDS += ROCM
endif
PointsLoader_DEPENDS := Framework DataFormats AlpakaCore AlpakaDataFormats
PointsLoaderValidator_DEPENDS := Framework AlpakaCore AlpakaDataFormats DataFormats
CLUEClusterizer_DEPENDS := Framework DataFormats AlpakaCore AlpakaDataFormats
