alpaka_EXTERNAL_DEPENDS := TBB ALPAKA BOOST BACKTRACE
ifdef CUDA_BASE
alpaka_EXTERNAL_DEPENDS += CUDA
endif
ifdef ROCM_BASE
alpaka_EXTERNAL_DEPENDS += ROCM
endif
CLUEClusterizer_DEPENDS := Framework DataFormats AlpakaCore AlpakaDataFormats
CLUEOutputProducer_DEPENDS := Framework DataFormats AlpakaCore AlpakaDataFormats
CLUEValidator_DEPENDS := Framework DataFormats AlpakaCore AlpakaDataFormats
