cuda_EXTERNAL_DEPENDS := TBB CUDA BOOST BACKTRACE
CLUEClusterizer_DEPENDS := Framework DataFormats CUDACore CUDADataFormats
CLUEOutputProducer_DEPENDS := Framework DataFormats CUDACore CUDADataFormats
CLUEValidator_DEPENDS := Framework DataFormats CUDACore CUDADataFormats
