serial_EXTERNAL_DEPENDS := TBB EIGEN BOOST BACKTRACE
CLUEClusterizer_DEPENDS := Framework DataFormats
CLUEOutputProducer_DEPENDS := Framework DataFormats
CLUEValidator_DEPENDS := Framework DataFormats
